apps/introduction/urls.py
from django.urls import path
from . import views

app_name = 'introduction'

urlpatterns = [
    path('', views.welcome, name='welcome')
]

apps/registration/urls.py
from django.urls import path
from . import views

app_name = 'registration'

urlpatterns = [
    path('login/', views.login_view, name='login'),
    path('signup/', views.signup_view, name='signup'),
    path('logout/', views.logout_view, name='logout')
]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.introduction.urls')),
    path('registration/', include('apps.registration.urls')),
    path('tests/', include('apps.tests.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/introduction/views.py
from django.shortcuts import render

# Create your views here.

def welcome(request):
    return render(request, 'introduction/welcome.html')

apps/introduction/templates/introduction/welcome.html
{% extends "base.html" %}
{% block title %}Introduction{% endblock %}

{% block content %}
<div class="text-2xl rounded-box mt-3 pt-8">
    <h1 style="line-height: 2">Вас вітає QuestionnerGame - гра, в якій ви повинні відповідати на запитання авторів відповідних тестів і отримувати бали.<br>
    Проаналізуйте правила гри:</h1>
</div>
<div class="text-3xl rounded-box text-secondary font-bold">
    1. Зареєструвати себе.<br>
    2. Зайти та зареєструватися на тест.<br>
    3. Відповісти на всі питання з тесту автора.<br>
    4. Отримати ваш загальний бал.<br>
    5. Ви можете заходити ще раз на тест того ж автора або на тест інших авторів.
</div>
<img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT8M7qV7TIX6_7Hr1I9MjPdtXZ1F7yvPnPazw&s" class="mt-5 w-full h-80 mb-4 rounded-box" alt="Image">
{% endblock %}

templates/_include_blocks/_nav_block.html
<div class="navbar bg-base-100">
    <div class="navbar-start">
      <a href="{% url 'introduction:welcome' %}" class="flex justfy-between">
        <img src="https://tse2.mm.bing.net/th?id=OIP.vgkW4qACiJ5tutDkyuBQCQHaE8&pid=Api&P=0&h=180" alt="Image" class="w-1/5 rounded-box">
        <p class="mt-4 ml-5 font-bold">QuestionnerGame</p>
      </a>
      <div class="flex justify-center dropdown m-3">
        <div tabindex="0" role="button" class="btn m-1">
          Theme
          <svg width="5px" height="5px" class="h-2 w-2 fill-current opacity-60 inline-block" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 2048 2048"><path d="M1799 349l242 241-1017 1017L7 590l242-241 775 775 775-775z"></path></svg>
        </div>
        <ul tabindex="0" class="dropdown-content z-[1] p-2 shadow-2xl bg-base-300 rounded-box w-40">
          <li><input type="radio" name="theme-dropdown" class="theme-controller btn btn-sm btn-block btn-ghost justify-start" aria-label="Smyk" value="cmyk"/></li>
          <li><input type="radio" name="theme-dropdown" class="theme-controller btn btn-sm btn-block btn-ghost justify-start" aria-label="Synthwave" value="synthwave"/></li>
        </ul>
      </div>
    </div>
    <div class="navbar-center hidden lg:flex">
      <ul class="menu menu-horizontal px-1">
        <li><a href="{% url "tests:test" %}" class="font-bold">Тести</a></li>
      </ul>
    </div>
    <div class="navbar-end hidden lg:flex">
   <div class="dropdown dropdown-end">
            {% if user.is_authenticated %}
              <button class="btn btn-primary font-bold">{{user.username}}</button>
              <ul tabindex="0" class="mt-3 z-[1] p-2 shadow menu menu-sm dropdown-content bg-base-100 rounded-box w-45">
                <li><a href="{% url 'registration:logout' %}" class="font-bold">Вийти</a></li>
              </ul>
            {% else %}
              <div class="dropdown dropdown-end">
                <button class="btn text-secondary font-serif">Увійти</button>
                <ul tabindex="0" class="mt-3 z-[1] p-2 shadow menu menu-sm dropdown-content bg-base-100 rounded-box w-45">
                  <li><a href="{% url 'registration:login' %}" class="text-secondary font-bold mb-2">Увійти</a></li>
                  <li><a href="{% url 'registration:signup' %}" class="text-secondary font-bold">Зареєструватися</a></li>
                </ul>
              </div>
            {% endif %}
        </div>
    </div>
</div>

templates/base.html
<!doctype html>
<html lang="en" data-theme="acid">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}Page{% endblock %} - QuestionnerGame</title>
    <link href="https://cdn.jsdelivr.net/npm/daisyui@4.11.1/dist/full.min.css" rel="stylesheet" type="text/css" />
    <script src="https://cdn.tailwindcss.com"></script>
  </head>
  <body>
    {% if user.superuser %}
    <a href="/admin/" class="btn bm-accent">Адмінка</a>
    {% endif %}
    {% include "_include_blocks/_nav_block.html" %}
    {% if messages %}
    <div class="toast toast-end">
      {% for message in messages %}
      <div class="alert alert-{{message.tags}}" role="alart">
        {% if message.tags == 'info' %}
        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" class="stroke-current shrink-0 w-6 h-6"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M13 16h-1v-4h-1m1-4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z"></path></svg>
        {% elif message.tags == 'success' %}
        <svg xmlns="http://www.w3.org/2000/svg" class="stroke-current shrink-0 h-6 w-6" fill="none" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z" /></svg>
        {% elif message.tags == 'warning' %}
        <svg xmlns="http://www.w3.org/2000/svg" class="stroke-current shrink-0 h-6 w-6" fill="none" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-3L13.732 4c-.77-1.333-2.694-1.333-3.464 0L3.34 16c-.77 1.333.192 3 1.732 3z" /></svg>
        {% elif message.tags == 'error' %}
        <svg xmlns="http://www.w3.org/2000/svg" class="stroke-current shrink-0 h-6 w-6" fill="none" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M10 14l2-2m0 0l2-2m-2 2l-2-2m2 2l2 2m7-2a9 9 0 11-18 0 9 9 0 0118 0z" /></svg>
        {% endif %}
        <span>{{message}}<span>
        <button class="btn btn-ghost btn-sm btn-circle" onclick="this.parentElement.remove()">X</button>
      </div>
      {% endfor %}
    </div>
    {% endif %}
    <div class="container mx-auto">
      {% block content %}{% endblock %}
    </div>
  </body>
</html>